trigger:
  branches:
    include:
      - main

variables:
  secureFilePath: $(secureFile.secureFilePath)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DownloadSecureFile@1
  name: secureFile
  displayName: 'Download secure file'
  inputs:
    secureFile: 'AAIMLAPPair.pem'
    
- task: DownloadSecureFile@1
  name: envFile 
  displayName: 'Download .env file'
  inputs:
    secureFile: '.env'


- script: |
    # Install the necessary dependencies
    sudo apt-get update
    sudo apt-get install -y unzip

    # Download and install the AWS CLI
    curl -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    unzip awscliv2.zip
    sudo ./aws/install --update
  displayName: 'Install AWS CLI'

- script: |
    DISCORD_BOT_TOKEN=$(cat $(envFile.secureFilePath) | grep DISCORD_BOT_TOKEN | cut -d '=' -f2)
    OPENAI_API_KEY=$(cat $(envFile.secureFilePath) | grep OPENAI_API_KEY | cut -d '=' -f2)
    # Connect to the EC2 instance
    chmod 600 $(secureFilePath)
    ssh -o StrictHostKeyChecking=no -i "$(secureFilePath)" ec2-user@ec2-13-56-196-184.us-west-1.compute.amazonaws.com << EOF

      # Ensuring old containers and images are removed
      docker stop aaimlap_container
      docker rm aaimlap_container
      docker container prune -f
      docker rmi aaimlap_image
      docker image prune --force

      sudo rm -rf ~/AAIMLAP
      sudo git clone https://github.com/Alambdasystem/AAIMLAP.git
      cd AAIMLAP
      

      # Build image
      docker build -t aaimlap_image . -f Dockerfile.txt
      docker run -d \
      --env DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN \
      --env OPENAI_API_KEY=$OPENAI_API_KEY \
      --name aaimlap_container \
      aaimlap_image

    EOF
  displayName: 'Update Docker container on EC2 instance'
