trigger:
  branches:
    include:
      - main

variables:
  secureFilePath: $(secureFile.secureFilePath)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DownloadSecureFile@1
  name: secureFile
  displayName: 'Download secure file'
  inputs:
    secureFile: 'AAIMLAP.pem'

- script: |
    # Install the necessary dependencies
    sudo apt-get update
    sudo apt-get install -y unzip

    # Download and install the AWS CLI
    curl -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    unzip awscliv2.zip
    sudo ./aws/install --update
  displayName: 'Install AWS CLI'

- script: |
    # Connect to the EC2 instance
    chmod 600 $(secureFilePath)
    ssh -o StrictHostKeyChecking=no -i "$(secureFilePath)" ec2-user@ec2-54-153-39-18.us-west-1.compute.amazonaws.com << EOF

      # Ensuring old containers and images are removed
      docker stop aaimlap_container
      docker rm aaimlap_container
      docker container prune -f
      docker rmi aaimlap_image
      docker image prune --force

      # Pulling the latest version of the git repo, building and deploying the new container
      cd AAIMLAP
      sudo git pull origin main

      # Build image
      docker build -t aaimlap_image . -f Dockerfile.txt
      docker run -d --name aaimlap_container -p 5000:5000 aaimlap_image

    EOF
  displayName: 'Update Docker container on EC2 instance'
