FROM python:3.10
# Allows us to see console logs in real time w/o buffer
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY . .

EXPOSE 5000
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]


